require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'it']

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true
